# Generated by Django 4.2.3 on 2023-08-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Shop_Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reservation_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
