# Generated by Django 4.2.3 on 2023-08-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Shop_Products', '0002_product_reservation_expiration_product_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reservation_expiration',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reserved',
        ),
    ]
