# Generated by Django 4.2.3 on 2023-07-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Shop_Users', '0005_alter_clients_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email Confirmed'),
        ),
    ]
