# Generated by Django 4.2.3 on 2023-08-25 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Shop_Products', '0003_remove_product_reservation_expiration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('E_Shop_Cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Shop_Products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='reserved_at',
        ),
        migrations.DeleteModel(
            name='ProductReservation',
        ),
    ]
