# Generated by Django 4.2.3 on 2023-08-26 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Shop_Cart', '0002_reservedproduct_remove_cartproduct_reserved_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservedproduct',
            old_name='reserved_until',
            new_name='expiration_time',
        ),
        migrations.RemoveField(
            model_name='reservedproduct',
            name='created_at',
        ),
    ]
