# Generated by Django 4.2.3 on 2023-08-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Shop_Cart', '0003_rename_reserved_until_reservedproduct_expiration_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedproduct',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
