# Generated by Django 4.2.3 on 2023-10-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Shop_Cart', '0004_reservedproduct_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_key',
        ),
        migrations.DeleteModel(
            name='ReservedProduct',
        ),
    ]
